project:
  type: website
  output-dir: site

website:
  favicon: img/logo.png

# website:
  # title: "quarto_web"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  #     - href: posts/index.qmd
  #       text: News

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    include-after-body: my-modules/pageviewcounter-final.html # working, instant, and private


